eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

server:
  port: 3301

spring:
  application:
    name: conf-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hlhutu/conf-server #配置文件所在仓库
          username: hlhutu@163.com #登录账号
          password: nocturne1997 #登录密码
          default-label: master #配置文件分支
          search-paths: springcloudstudy  #配置文件所在根目录